# Task 1

A template code for calculating FCFs for $H_2$ - $H_2^+$ using the harmonic oscillator approximation. 

Imports:

In [1]:
import numpy as np
import matplotlib.pyplot as plt

from FCF_helper import FCFSpec

Initialize the `FCFSpec` object. Modify `n_0_max` and `n_p_max` (the maximum vibrational states of $H_2$ and $H_2^+$ that we'll look at calculating FCFs for) in order to get 10 transitions starting from n_0=0.

In [2]:
n_0_max = 2
n_p_max = 2

fcfspec = FCFSpec(n_0_max, n_p_max)

Calculate all the FCFs and print the results.

In [3]:
spectrum = fcfspec.spectrum_analysis()
print("n_0\t\t n_p\t\t FCF")
print(spectrum)

n_0		 n_p		 FCF
[[0.00000000e+00 0.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00 2.95139079e+00]
 [0.00000000e+00 2.00000000e+00 3.49048846e+00]
 [1.00000000e+00 0.00000000e+00 1.55717551e+00]
 [1.00000000e+00 1.00000000e+00 1.42278254e+00]
 [1.00000000e+00 2.00000000e+00 4.36585159e-04]
 [2.00000000e+00 0.00000000e+00 1.74174773e+00]
 [2.00000000e+00 1.00000000e+00 3.46957789e-01]
 [2.00000000e+00 2.00000000e+00 5.00381497e-01]]
